Python 3: when redirect_url unexpectedly is bytes, turn it into native string before comparing.
Otherwise you get a traceback:

```
  File ".../pas/plugins/headers/plugins.py", line 142, in challenge
    if '//' not  in url:
TypeError: a bytes-like object is required, not 'str'
```